name: Functional tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ "$RUNNER_OS" = "macOS" ]
        then
          brew install sdl
        elif [ "$RUNNER_OS" = "Linux" ]
        then
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends \
            python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev \
            libsdl-ttf2.0-dev libportmidi-dev libfreetype6-dev
        fi
        pip install numpy pygame

    - name: Run functional tests
      run: ./run-tests
