name: Static code analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  codeql:
    name: Scan code with CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    # For PRs, checkout the PR's head instead of the merge commit.
    - name: Checkout pull request head
      if: github.event_name == 'pull_request'
      run: git checkout HEAD^2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
        queries: security-and-quality

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1
